#! /bin/sh

### BEGIN INIT INFO
# Provides:          socnet
# Required-Start:    
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
### END INIT INFO

set -e

kill_if_exist () {
    for PID in `ps ax | grep  "$1" | grep -v grep | cut -c-6`
    do
        kill -9 $PID
    done
}

case "$1" in
  start|restart)
    cd /var/socnet/appserver/app
    sudo -u appserver bash -c "source venv/bin/activate"
    kill_if_exist "manage.py celeryd"
    sudo -u appserver python manage.py celeryd > /dev/null 2>/var/socnet/appserver/celeryd-err.log &
    kill_if_exist "uwsgi"
    sudo -u appserver uwsgi -s /var/socnet/appserver/uwsgi.sock -C -H venv -x django.xml -M -p 16 -l 16384 > /dev/null 2>/var/socnet/appserver/uwsgi-err.log &
    ;;
  stop)
    kill_if_exist "uwsgi"
    kill_if_exist "manage.py celeryd"
    ;;
  *)
    echo "Usage: /etc/init.d/socnet {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
